language: node_js
cache:
  directories:
    - ~!@/.npm
node_js:
  - "10.15.3"
git:
  depth: 3
script:
  - yarn build
  - echo 'url-personalizada.com' > public/CNAME
deploy:
  provider: pages
  skip-cleanup: true
  keep: true
  github-token: $GITHUB_TOKEN
  local_dir: dist/
  target-branch: master
  commit_message: "Deploy release ${TRAVIS_TAG}"
  on:
    branch: develop
